/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NicknameDialog: typeof import('./src/components/nicknameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoteDialog: typeof import('./src/components/voteDialog.vue')['default']
  }
}
